import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {Suspense} from "react";
import Loading from "@/app/loading";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "UIU Helpline",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-center items-center w-full min-h-screen`}
            >
            <Navbar/>
            <div className="flex-1 w-full flex justify-center ">
                <Suspense fallback={<Loading />}>{children}</Suspense>

            </div>
            <Footer/>
            </body>
            </html>

        </ClerkProvider>
    );
}
